### ISSUE TITLE
Change the language of the application

### ISSUE THREAD

**Issue by ghost** [SkyTubeTeam/SkyTube#1077]
You cannot change the application language in the settings.

**Comment by drogga** [comment]
Yes, @gzsombor add an option to finally be able to change the UI display language of SkyTube please, I want it in English on all of my devices, but purposely not all of them are in English.

**Comment by drogga** [comment]
@gzsombor
I saw the commit related to this and tested the snapshots, but trying to go to the Video Player Setting causes the following crash and Channel Blocker's preferred language doesn't work, nothing can be selected (single or multiple):
```
FATAL EXCEPTION: main
Process: free.rm.skytube.oss.snapshot, PID: 823
java.lang.IllegalArgumentException: list[22] is a repetition
	at android.os.LocaleList.<init>(LocaleList.java:195)
	at androidx.core.os.LocaleListCompat$Api24Impl.createLocaleList(LocaleListCompat.java:341)
	at androidx.core.os.LocaleListCompat.create(LocaleListCompat.java:77)
	at androidx.core.os.LocaleListCompat.forLanguageTags(LocaleListCompat.java:172)
	at free.rm.skytube.gui.fragments.preferences.VideoPlayerPreferenceFragment.configureLanguageSelector(VideoPlayerPreferenceFragment.java:100)
	at free.rm.skytube.gui.fragments.preferences.VideoPlayerPreferenceFragment.onCreatePreferences(VideoPlayerPreferenceFragment.java:74)
	at androidx.preference.PreferenceFragmentCompat.onCreate(PreferenceFragmentCompat.java:160)
	at androidx.fragment.app.Fragment.performCreate(Fragment.java:2949)
	at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:475)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:278)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2189)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2100)
	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:2002)
	at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:524)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:237)
	at android.app.ActivityThread.main(ActivityThread.java:7948)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1075)
```

**Comment by drogga** [comment]
Oh and Please update the workflow to use v4 of the artifact actions.

**Comment by gzsombor** [comment]
Thanks for testing! 
Yeah, the beauty of Android development: I've just tested on Android emulator on API 19 - where it worked correctly.

**Comment by drogga** [comment]
That new "Application Language" setting should be in Preferences > Others, not in Video Player.
It now seems to change for most of the elements, except all the tabs and hiding/unhiding all the tabs doesn't fix it unfortunately.
The "Default content country" should also be moved to "Others" as it's not related to the Video Player as well.

Preferences > Video Blocker > Preferred Language(s) => How do I use this @gzsombor  ?, it doesn't seem to allow me to select anything, single or multiple, the list just scrolls up and down and that's it, the 2 "Select All" and "Select None" buttons don't absolutely do anything.

The main screen's 3-dots context menu with the 3 options now seem like a new material layer over the old one, you can notice 2 old top and bottom strips with darker gray color.

Subscribing to a channel (which btw doesn't show the subscribers count inside) gets doubled/tripled/+ in the Subscriptions pane when using the Video Blocker button.

Please do some testings with newer Android versions than 4.4 and with a clean install, not updated over an old version.

**Comment by gzsombor** [comment]
I think this issue is fixed now, the application language can be selected in the preferences.

**Comment by drogga** [comment]
Yeah, when you ignore my comments..., but even then if you count only the OP - it's still buggy AH !, but closing is easier, so you just did that and I doubt that you will start reading. Why do I even bother reporting stuff ?...
