### ISSUE TITLE
Watching Downloads with Sponsorblock enabled leads to crash

### ISSUE THREAD

**Issue by RandomModderJDK** [SkyTubeTeam/SkyTube#1191]
**Describe the bug**
If you try to watch a download, that was downloaded with SponsorBlock disabled, with SponsorBlock enabled now it crashes.

**To Reproduce**
1. Make sure SponsorBlock is disabled in settings
2. Download a video
3. Enable SponsorBlock in settings
4. Open the download

**Expected behavior**
The video just opens, either fetches the sponsorblock data afterwards, or doesnt enable sponsorblock for the video at all. Or even ask the user. You could maybe add a default setting.

**Setup:**
 - Android version: 12
 - Is Your device rooted? No
 - Do You use Tor or any VPN service with your device? No
 - App source [e.g. FDroid, Downloaded from GitHub, self build] Github
 - App Version [e.g. v2.977] v2.986
 - App Flavour [e.g. Extra or OSS] Extra

**Additional context**
Logcat output:
```FATAL EXCEPTION: main
Process: free.rm.skytube.extra, PID: 28692
java.lang.NullPointerException: Attempt to get length of null array
	at java.lang.StringFactory.newStringFromBytes(StringFactory.java:46)
	at free.rm.skytube.businessobjects.db.DownloadedVideosDb.getDownloadedVideoSponsorblock(DownloadedVideosDb.java:211)
	at free.rm.skytube.gui.fragments.YouTubePlayerV2Fragment.lambda$loadVideo$10(YouTubePlayerV2Fragment.java:548)
	at free.rm.skytube.gui.fragments.YouTubePlayerV2Fragment.$r8$lambda$maH0k_as0ghhg2HTMDXsWbCRjrY(YouTubePlayerV2Fragment.java:0)
	at free.rm.skytube.gui.fragments.YouTubePlayerV2Fragment$$ExternalSyntheticLambda9.accept(R8$$SyntheticClass:0)
	at io.reactivex.rxjava3.internal.observers.ConsumerSingleObserver.onSuccess(ConsumerSingleObserver.java:62)
	at io.reactivex.rxjava3.internal.operators.single.SingleOnErrorReturn$OnErrorReturn.onSuccess(SingleOnErrorReturn.java:82)
	at io.reactivex.rxjava3.internal.operators.single.SingleObserveOn$ObserveOnSingleObserver.run(SingleObserveOn.java:81)
	at io.reactivex.rxjava3.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:123)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:233)
	at android.os.Looper.loop(Looper.java:344)
	at android.app.ActivityThread.main(ActivityThread.java:8212)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
```

**Comment by gzsombor** [comment]
Thanks for the report, luckily, it seems, it's not hard to fix it!
