### ISSUE TITLE
App crashed when load comment

### ISSUE THREAD

**Issue by TruongTanLuc201270** [SkyTubeTeam/SkyTube#1240]
https://github.com/SkyTubeTeam/SkyTube/assets/145727083/7b936e74-d181-48b8-8307-c333815572d0

**Comment by tervor** [comment]
I experience the same issue here on Android 13. I managed to get a stack trace from the logs. Hopefully this is useful:
```
04-20 10:00:51.709  9483  9483 E AndroidRuntime: FATAL EXCEPTION: main
04-20 10:00:51.709  9483  9483 E AndroidRuntime: Process: free.rm.skytube.oss, PID: 9483
04-20 10:00:51.709  9483  9483 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String org.schabi.newpipe.extractor.stream.Description.getContent()' on a null object reference
04-20 10:00:51.709  9483  9483 E AndroidRuntime: 	at free.rm.skytube.gui.businessobjects.adapters.CommentsAdapter$CommentViewHolder.updateInfo(Unknown Source:108)
04-20 10:00:51.709  9483  9483 E AndroidRuntime: 	at free.rm.skytube.gui.businessobjects.adapters.CommentsAdapter.getGroupView(Unknown Source:13)
04-20 10:00:51.709  9483  9483 E AndroidRuntime: 	at android.widget.ExpandableListConnector.getView(ExpandableListConnector.java:446)
04-20 10:00:51.709  9483  9483 E AndroidRuntime: 	at android.widget.AbsListView.obtainView(AbsListView.java:2458)
04-20 10:00:51.709  9483  9483 E AndroidRuntime: 	at android.widget.ListView.makeAndAddView(ListView.java:2067)
04-20 10:00:51.709  9483  9483 E AndroidRuntime: 	at android.widget.ListView.fillDown(ListView.java:793)
04-20 10:00:51.709  9483  9483 E AndroidRuntime: 	at android.widget.ListView.fillFromTop(ListView.java:855)
04-20 10:00:51.709  9483  9483 E AndroidRuntime: 	at android.widget.ListView.layoutChildren(ListView.java:1810)
04-20 10:00:51.709  9483  9483 E AndroidRuntime: 	at android.widget.AbsListView.onLayout(AbsListView.java:2255)
04-20 10:00:51.709  9483  9483 E AndroidRuntime: 	at android.view.View.layout(View.java:23798)
04-20 10:00:51.709  9483  9483 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6413)
04-20 10:00:51.709  9483  9483 E AndroidRuntime: 	at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1103)
04-20 10:00:51.709  9483  9483 E AndroidRuntime: 	at android.view.View.layout(View.java:23798)
04-20 10:00:51.709  9483  9483 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6413)
04-20 10:00:51.709  9483  9483 E AndroidRuntime: 	at hollowsoft.slidingdrawer.SlidingDrawer.onLayout(Unknown Source:93)
04-20 10:00:51.709  9483  9483 E AndroidRuntime: 	at android.view.View.layout(View.java:23798)
04-20 10:00:51.709  9483  9483 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6413)
04-20 10:00:51.709  9483  9483 E AndroidRuntime: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
04-20 10:00:51.709  9483  9483 E AndroidRuntime: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
04-20 10:00:51.709  9483  9483 E AndroidRuntime: 	at android.view.View.layout(View.java:23798)
04-20 10:00:51.709  9483  9483 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6413)
04-20 10:00:51.709  9483  9483 E AndroidRuntime: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
04-20 10:00:51.709  9483  9483 E AndroidRuntime: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
04-20 10:00:51.709  9483  9483 E AndroidRuntime: 	at android.view.View.layout(View.java:23798)
04-20 10:00:51.709  9483  9483 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6413)
04-20 10:00:51.709  9483  9483 E AndroidRuntime: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
04-20 10:00:51.709  9483  9483 E AndroidRuntime: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
04-20 10:00:51.709  9483  9483 E AndroidRuntime: 	at android.view.View.layout(View.java:23798)
04-20 10:00:51.709  9483  9483 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6413)
04-20 10:00:51.709  9483  9483 E AndroidRuntime: 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1891)
04-20 10:00:51.709  9483  9483 E AndroidRuntime: 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1729)
04-20 10:00:51.709  9483  9483 E AndroidRuntime: 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1638)
04-20 10:00:51.709  9483  9483 E AndroidRuntime: 	at android.view.View.layout(View.java:23798)
04-20 10:00:51.709  9483  9483 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6413)
04-20 10:00:51.709  9483  9483 E AndroidRuntime: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
04-20 10:00:51.709  9483  9483 E AndroidRuntime: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
04-20 10:00:51.709  9483  9483 E AndroidRuntime: 	at android.view.View.layout(View.java:23798)
04-20 10:00:51.709  9483  9483 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6413)
04-20 10:00:51.709  9483  9483 E AndroidRuntime: 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1891)
04-20 10:00:51.709  9483  9483 E AndroidRuntime: 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1729)
04-20 10:00:51.709  9483  9483 E AndroidRuntime: 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1638)
04-20 10:00:51.709  9483  9483 E AndroidRuntime: 	at android.view.View.layout(View.java:23798)
04-20 10:00:51.709  9483  9483 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6413)
04-20 10:00:51.709  9483  9483 E AndroidRuntime: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
04-20 10:00:51.709  9483  9483 E AndroidRuntime: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
04-20 10:00:51.709  9483  9483 E AndroidRuntime: 	at com.android.internal.policy.DecorView.onLayout(DecorView.java:799)
04-20 10:00:51.709  9483  9483 E AndroidRuntime: 	at android.view.View.layout(View.java:23798)
04-20 10:00:51.709  9483  9483 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6413)
04-20 10:00:51.709  9483  9483 E AndroidRuntime: 	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:4118)
04-20 10:00:51.709  9483  9483 E AndroidRuntime: 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3459)
04-20 10:00:51.709  9483  9483 E AndroidRuntime: 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2371)
04-20 10:00:51.709  9483  9483 E AndroidRuntime: 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9297)
04-20 10:00:51.709  9483  9483 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1231)
04-20 10:00:51.709  9483  9483 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1239)
04-20 10:00:51.709  9483  9483 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:899)
04-20 10:00:51.709  9483  9483 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:832)
04-20 10:00:51.709  9483  9483 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1214)
04-20 10:00:51.709  9483  9483 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:942)
04-20 10:00:51.709  9483  9483 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
04-20 10:00:51.709  9483  9483 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:201)
04-20 10:00:51.709  9483  9483 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:288)
04-20 10:00:51.709  9483  9483 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7918)
04-20 10:00:51.709  9483  9483 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
04-20 10:00:51.709  9483  9483 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
04-20 10:00:51.709  9483  9483 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
04-20 10:00:51.715  1486  8800 W ActivityTaskManager:   Force finishing activity free.rm.skytube.oss/free.rm.skytube.gui.activities.YouTubePlayerActivity

```

**Comment by drogga** [comment]
Guys, the NewPipeExtractor was updated 2 weeks ago, but a new release wasn't made, you can test the latest CI (GH Actions) debug build before the files expire to see if that fixes the comments loading...
BTW - Yes, trying to load them crashes the app for me as well, but I'm avoiding swiping left to show them at the moment, untill a proper release is being published here, tho sometimes I do the gesture by mistake and ofc. it crashes it, which is an annoyance, but I have hopes...

**Comment by tervor** [comment]
@drogga I shortly tested the SkyTube Extra version from build 538 and it does not crash when displaying the comments, but it is not showing the comments correctly. See the screen shot:
![Screenshot_20240421-171613_1](https://github.com/SkyTubeTeam/SkyTube/assets/1598708/e208f660-b302-40c5-a167-ab9f10a88654)

**Comment by drogga** [comment]
@gzsombor
I looks like NP updated the Extractor along with the new ver., you might consider doing the same here, but I hope you have time to handle the Audio ML thing anytime soon.
Thank You !

**Comment by gzsombor** [comment]
After upgrading to the latest NewPipeExtractor it seems to be working again.
