### ISSUE TITLE
Import Issues

### ISSUE THREAD

**Issue by BlueFeather89** [SkyTubeTeam/SkyTube#362]
Bug Description: App feature not working.

Steps to Reproduce:
1. Install and launch the app.
2. Tap on "Feed"
3. Tap on Import Subscription from "Youtube".
4. Follow the instructions and tap on Select Subscription file.

Actual Result: Observe that App displays "Failed to Import your Youtube Subscription".
Expected Result: App features should work as intended.

Bug Description: App feature not working.

Steps to Reproduce:
1. Install and launch the app.
2. Tap on "Feed"
3. Tap on "Import  Backup".

Actual Result: Observe that App displays "Failed to import your database".
Expected Result: App features should work as intended.

**Comment by ram-on** [comment]
@BlueFeather89 Can you kindly confirm that the following alert box / dialog is being displayed when you tap on "Import Subscription from YouTube" / "Import Backup":  https://i.imgur.com/zkCb009.jpg
?

_I get "Failed to Import your Youtube Subscription" when I tap on the "Deny" button._

**Comment by blitztide** [comment]
I have a similar issue importing backups:
```
01-15 14:15:06.552  9108  9108 E SubscriptionsBackupsManager: Unable to import the databases...
01-15 14:15:06.552  9108  9108 E SubscriptionsBackupsManager: java.util.zip.ZipException: invalid block type
01-15 14:15:06.552  9108  9108 E SubscriptionsBackupsManager:   at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:183)
01-15 14:15:06.552  9108  9108 E SubscriptionsBackupsManager:   at java.util.zip.ZipInputStream.read(ZipInputStream.java:208)
01-15 14:15:06.552  9108  9108 E SubscriptionsBackupsManager:   at java.io.FilterInputStream.read(FilterInputStream.java:107)
01-15 14:15:06.552  9108  9108 E SubscriptionsBackupsManager:   at free.rm.skytube.gui.businessobjects.preferences.ZipFile.copyStream(ZipFile.java:103)
01-15 14:15:06.552  9108  9108 E SubscriptionsBackupsManager:   at free.rm.skytube.gui.businessobjects.preferences.ZipFile.unzip(ZipFile.java:91)
01-15 14:15:06.552  9108  9108 E SubscriptionsBackupsManager:   at free.rm.skytube.gui.businessobjects.preferences.BackupDatabases.importBackupDb(BackupDatabases.java:152)
01-15 14:15:06.552  9108  9108 E SubscriptionsBackupsManager:   at free.rm.skytube.gui.businessobjects.SubscriptionsBackupsManager.lambda$importDatabases$5(SubscriptionsBackupsManager.java:197)
01-15 14:15:06.552  9108  9108 E SubscriptionsBackupsManager:   at free.rm.skytube.gui.businessobjects.-$$Lambda$SubscriptionsBackupsManager$Nj-Nr02AMWVhziAm5iBWdPRChVE.call(Unknown Source:2)
01-15 14:15:06.552  9108  9108 E SubscriptionsBackupsManager:   at io.reactivex.rxjava3.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:43)
01-15 14:15:06.552  9108  9108 E SubscriptionsBackupsManager:   at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
01-15 14:15:06.552  9108  9108 E SubscriptionsBackupsManager:   at io.reactivex.rxjava3.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
01-15 14:15:06.552  9108  9108 E SubscriptionsBackupsManager:   at io.reactivex.rxjava3.core.Scheduler$DisposeTask.run(Scheduler.java:614)
01-15 14:15:06.552  9108  9108 E SubscriptionsBackupsManager:   at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65)
01-15 14:15:06.552  9108  9108 E SubscriptionsBackupsManager:   at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:56)
01-15 14:15:06.552  9108  9108 E SubscriptionsBackupsManager:   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
01-15 14:15:06.552  9108  9108 E SubscriptionsBackupsManager:   at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
01-15 14:15:06.552  9108  9108 E SubscriptionsBackupsManager:   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
01-15 14:15:06.552  9108  9108 E SubscriptionsBackupsManager:   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
01-15 14:15:06.552  9108  9108 E SubscriptionsBackupsManager:   at java.lang.Thread.run(Thread.java:919)
```
From what I can see, the <date>.skytube files are meant to be a .zip file with: .db files and preferences.json

A fresh install of skytube with no subscriptions seems to generate a valid file, however a file exported from the same version with feeds doesn't seem to be valid.

**Comment by blitztide** [comment]
I've had a look through the exported database in a hex editor, the zip headers seem to all be pointing to subs.db and not the correct individual files.
```
0000:0000 | 50 4B 03 04  14 00 08 08  08 00 2D 72  2F 52 00 00 | PK........-r/R..
0000:0010 | 00 00 00 00  00 00 00 00  00 00 07 00  00 00 73 75 | ..............su
0000:0020 | 62 73 2E 64  62                                    | bs.db           
0000:8000 | 50 4B 03 04  14 00 08 08  08 00 2D 72  2F 52 00 00 | PK........-r/R..
0000:8010 | 00 00 00 00  00 00 00 00  00 00 07 00  00 00 73 75 | ..............su
0000:8020 | 62 73 2E 64  62                                    | bs.db           
0005:A000 | 50 4B 03 04  14 00 08 08  08 00 2D 72  2F 52 00 00 | PK........-r/R..
0005:A010 | 00 00 00 00  00 00 00 00  00 00 07 00  00 00 73 75 | ..............su
0005:A020 | 62 73 2E 64  62                                    | bs.db           
```

**Comment by gzsombor** [comment]
@blitztide : what version do you use for export? The latest?

**Comment by blitztide** [comment]
That was exported on: 2.976 Extra (2021-01-05 21:46)

**Comment by blitztide** [comment]
Here's a logcat when it's running the backup:
```
01-15 20:26:55.499 20535 20772 D ZipOutput: Added: /mnt/expand/83be6bb1-25de-4c39-8545-9561cb434305/user/0/free.rm.skytube.extra/databases/subs.db
01-15 20:26:55.502 20535 20772 D ZipOutput: Added: /mnt/expand/83be6bb1-25de-4c39-8545-9561cb434305/user/0/free.rm.skytube.extra/databases/bookmarks.db
01-15 20:26:55.507 20535 20772 D ZipOutput: Added: /mnt/expand/83be6bb1-25de-4c39-8545-9561cb434305/user/0/free.rm.skytube.extra/databases/playbackhistory.db
01-15 20:26:55.509 20535 20772 D ZipOutput: Added: /mnt/expand/83be6bb1-25de-4c39-8545-9561cb434305/user/0/free.rm.skytube.extra/databases/channelFiltering.db
01-15 20:26:55.511 20535 20772 D ZipOutput: Added: /mnt/expand/83be6bb1-25de-4c39-8545-9561cb434305/user/0/free.rm.skytube.extra/databases/searchHistory.db
01-15 20:26:55.512 20535 20772 I BackupDatabases: Saving pref_use_default_newpipe_backend as true
01-15 20:26:55.512 20535 20772 I BackupDatabases: Saving pref_key_subscriptions_alphabetical_order as false
01-15 20:26:55.512 20535 20772 I BackupDatabases: Saving pref_youtube_api_key as null
01-15 20:26:55.512 20535 20772 I BackupDatabases: Saving pref_default_tab_name as MainFragment.featuredVideosFragment
01-15 20:26:55.512 20535 20772 I BackupDatabases: Saving pref_key_switch_volume_and_brightness as null
01-15 20:26:55.512 20535 20772 I BackupDatabases: Saving pref_key_screen_gestures as null
01-15 20:26:55.512 20535 20772 I BackupDatabases: Saving pref_key_mobile_network_usage_policy as allow
01-15 20:26:55.512 20535 20772 I BackupDatabases: Saving pref_key_download_to_separate_directories as false
01-15 20:26:55.513 20535 20772 I BackupDatabases: Saving pref_key_video_download_folder as null
01-15 20:26:55.513 20535 20772 I BackupDatabases: Saving pref_minimum_resolution as -1
01-15 20:26:55.513 20535 20772 I BackupDatabases: Saving pref_maximum_resolution as 5
01-15 20:26:55.513 20535 20772 I BackupDatabases: Saving pref_key_video_quality as BEST_QUALITY
01-15 20:26:55.513 20535 20772 I BackupDatabases: Saving pref_minimum_resolution_mobile as null
01-15 20:26:55.513 20535 20772 I BackupDatabases: Saving pref_maximum_resolution_mobile as null
01-15 20:26:55.513 20535 20772 I BackupDatabases: Saving pref_key_video_quality_on_mobile as LEAST_BANDWITH
01-15 20:26:55.513 20535 20772 I BackupDatabases: Saving pref_key_video_minimum_resolution as null
01-15 20:26:55.513 20535 20772 I BackupDatabases: Saving pref_key_video_maximum_resolution as null
01-15 20:26:55.513 20535 20772 I BackupDatabases: Saving pref_key_video_quality_for_downloads as BEST_QUALITY
01-15 20:26:55.513 20535 20772 I BackupDatabases: Saving pref_hide_tabs as null
01-15 20:26:55.515 20535 20772 D ZipOutput: Added: preferences.json
01-15 20:26:56.817 20535 20556 D OpenGLRenderer: endAllActiveAnimators on 0x85a75400 (RippleDrawable) with handle 0x9df432d0
```

**Comment by blitztide** [comment]
The issue only seems to happen when I have subscriptions added, it exported correctly without subscriptions.
However when I have my subscriptions added it doesn't export correctly.

If you add this subs.db to a working zip folder, then export you should get the same result.
[subs.db.zip](https://github.com/ram-on/SkyTube/files/5822810/subs.db.zip)

Tested on Version: 2.976 Extra on Xiaomi Redmi 6a and LG Nexus 5X

**Comment by gzsombor** [comment]
It's very strange. I've imported your subs.db, and after I've re-exported, and imported again, etc, but it seems to be working fine in a emulator. Maybe, this could be a multi-threading issue during export, somehow the export run in the same time, multiple? I don't see how that could happened, but the export/import functionality recently changed a bit - in 2.976, with the introduction of RxJava.

**Comment by blitztide** [comment]
I have tested import and export on the new version and it appears to work correctly.

**Comment by gzsombor** [comment]
Thanks for the verification @blitztide  !
