### ISSUE TITLE
App crash while updating feed

### ISSUE THREAD

**Issue by malloy139** [SkyTubeTeam/SkyTube#934]
**Describe the bug**
After opening skytube the feed automatically updates. After 5 or 6 channels of about 200 the app crashes.

**Setup:**
 - Android version: 
 10
 - Is Your device rooted?
 Yes
 - Do You use Tor or any VPN service with your device?
 No
 - App source 
 FDroid
 - App Version
 v2.977
 - App Flavour 
 OSS

**Comment by malloy139** [comment]
The problem seems to be a channel that no longer exists. This is in logcat:

FATAL EXCEPTION: main
Process: free.rm.skytube.oss, PID: 6384
io.reactivex.rxjava3.exceptions.OnErrorNotImplementedException: The exception was not handled due to missing onError handler in the subscribe() method call. Further reading: https://github.com/ReactiveX/RxJava/wiki/Error-Handling | free.rm.skytube.businessobjects.YouTube.newpipe.NewPipeException: Getting videos for UCeCbD5FRtwgZu__LqLtQj7Q fails:Got error: "This channel does not exist."
	at io.reactivex.rxjava3.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:717)
	at io.reactivex.rxjava3.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:714)
	at io.reactivex.rxjava3.internal.observers.ConsumerSingleObserver.onError(ConsumerSingleObserver.java:46)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableToListSingle$ToListSubscriber.onError(FlowableToListSingle.java:96)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableDoOnEach$DoOnEachSubscriber.onError(FlowableDoOnEach.java:111)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableObserveOn$BaseObserveOnSubscriber.checkTerminated(FlowableObserveOn.java:209)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableObserveOn$ObserveOnSubscriber.runAsync(FlowableObserveOn.java:394)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableObserveOn$BaseObserveOnSubscriber.run(FlowableObserveOn.java:176)
	at io.reactivex.rxjava3.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:123)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)
Caused by: free.rm.skytube.businessobjects.YouTube.newpipe.NewPipeException: Getting videos for UCeCbD5FRtwgZu__LqLtQj7Q fails:Got error: "This channel does not exist."
	at free.rm.skytube.businessobjects.YouTube.newpipe.NewPipeService.getChannelPager(NewPipeService.java:207)
	at free.rm.skytube.businessobjects.YouTube.newpipe.NewPipeService.getChannelDetails(NewPipeService.java:240)
	at free.rm.skytube.businessobjects.db.DatabaseTasks.lambda$getChannelInfo$3(DatabaseTasks.java:85)
	at free.rm.skytube.businessobjects.db.-$$Lambda$DatabaseTasks$Bt5VP0p4aAbz71Tw-GBTc41eBoA.call(Unknown Source:6)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeFromCallable.subscribeActual(MaybeFromCallable.java:47)
	at io.reactivex.rxjava3.core.Maybe.subscribe(Maybe.java:5330)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeSubscribeOn$SubscribeTask.run(MaybeSubscribeOn.java:54)
	at io.reactivex.rxjava3.core.Scheduler$DisposeTask.run(Scheduler.java:614)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:56)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)
Caused by: org.schabi.newpipe.extractor.exceptions.ContentNotAvailableException: Got error: "This channel does not exist."
	at org.schabi.newpipe.extractor.services.youtube.YoutubeParsingHelper.defaultAlertsCheck(YoutubeParsingHelper.java:648)
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeChannelExtractor.onFetchPage(YoutubeChannelExtractor.java:108)
	at org.schabi.newpipe.extractor.Extractor.fetchPage(Extractor.java:54)
	at free.rm.skytube.businessobjects.YouTube.newpipe.NewPipeService.getChannelExtractor(NewPipeService.java:279)
	at free.rm.skytube.businessobjects.YouTube.newpipe.NewPipeService.getChannelPager(NewPipeService.java:202)
	... 14 more

**Comment by gzsombor** [comment]
Thanks for the detailed exception, I could reproduce the problem with that given channel id, and luckily, it's already fixed in a recent commit, where I've improved the subscription fetching [here](https://github.com/SkyTubeTeam/SkyTube/commit/522d1cf677490f65b630518840220d41596a5c99)
